---
- name: Install the required packages in RedHat derivatives
  yum: name={{item}} state=installed
  with_items: '{{sshd_pkgs}}'

- name: Ensure selinux is complient with non-default port
  seport:
        ports: "{{sshd.listen.ports|join(',')}}"
        proto: "tcp"
        setype: ssh_port_t
        state : present


